name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Corrected: specify v2 properly

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"  # Corrected quotes and *3.x* syntax

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  
        pip install -r requirements.txt  # Corrected requirements.txt spacing and syntax

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"  # Corrected to find all tests that match "test_*.py" in the current directory

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Corrected syntax: always()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Corrected syntax

    - name: Deploy Application
      run: |
        echo "Deploying the application..."  # Placeholder message for deployment
        # Replace this with actual deployment steps
